### ISSUE TITLE
Learning how to learn efficiently

### ISSUE THREAD

**Issue by juggernaut451** [GNDG/talks#12]
## Title
Learning how to learn efficiently

## Brief description of the content to be covered
- Why is learning important for developers
- What are the different way to enhance your learning skill
- How the human body works while we learn

## Time required for the talk
30 mins

## About yourself

[http://juggernaut451.com](http://juggernaut451.com)

## Any comments
All developers are in process of learning new things. Here time plays a vital role. One could save time if learning could be done efficiently. Discussing the challenges and importance of learning one could get to the goal faster.

This would be an unconventional talk to be allowed into PyDelhi's meetups. However, one I believe the developer need.

**Comment by aaqaishtyaq** [comment]
As this talk is delivered, I'm closing this issue.

**Comment by aaqaishtyaq** [comment]
@juggernaut451 Any requirements from our side?
