### ISSUE TITLE
How Internet Works

### ISSUE THREAD

**Issue by vsnehil92** [GNDG/talks#13]
Title
How Internet Works

A brief description of the internet helps you get into web development. All web developers at the end want to become a full stack developer, but we don't look at the basics of how the things are working internally so it is important for everyone to have the knowledge of the internal working of the technology they are working on.

Link to slides / demos / any other content (if any)
About yourself
http://vsnehil92.github.io

Any comments
The audience who a going for web development in the future is welcome to attend the talk.

**Comment by aaqaishtyaq** [comment]
@vsnehil92 Any requirements from our side?
