### ISSUE TITLE
[TALK]  Find the wonders in - CSS

### ISSUE THREAD

**Issue by rajataaron** [GNDG/talks#6]
**Description-**
This talk is about the Fundamentals of CSS purely for beginners. Frontend always plays a vital role in product development. And through CSS you can achieve your daily goals.

**Prerequisites -**
Good understanding of HTML and a little bit of CSS.

**What will this session cover?**
This session is purely for beginners so I will cover some quick and short CSS tricks in this session.

**Time -**
30-40 mins for talk

**About Me**
I am a Frontend developer at Contify. I have 1+ year of experience in frontend and 8+ months in UX/UI. Rest you can find about me at my [website](www.rajatsaini.com).

**Comment by aaqaishtyaq** [comment]
@rajataaron would you be able to deliver this talk on 28th July?

**Comment by rajataaron** [comment]
@aaqaishtyaq i ahve already delivered this talk at NIET.

**Comment by aaqaishtyaq** [comment]
As this talk is delivered, I think we should close this issue.
